name: Hello World Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install pytest
          pip install pylint

      # Run echo command
      - name: Run Echo
        run: echo "Hello, world!"

      # Run tests (make sure tests exist in the correct directory)
      - name: Run Test
        run: pytest  # Or specify the test directory if needed (e.g., 'pytest tests/')

      # Lint code
      - name: Lint Code
        run: pylint src/  # Replace 'src/' with your code directory

      # Build project
      - name: Build Project
        run: docker build .